### ISSUE TITLE
Improve github-actions activation documentation

### ISSUE THREAD

**Issue by GabLeRoux** [Unity-CI/Website#46]
**Is your feature request related to a problem? Please describe.**
I feel like splitting the steps outside of the file makes it a bit confusing to know where to place these steps when you're starting with Github Actions.

**Describe the solution you'd like**

See section with a blue square in the following picture:

![image](https://user-images.githubusercontent.com/1264761/95375676-ef2cff00-08ad-11eb-9a5c-62a83a711dc9.png)

Combining examples into a single file would make it easier to go through the activation process and may reduce confusion about where to place the content.

**Describe alternatives you've considered**
* It would also be nice to be able to download that file, but this is definitely optional.

This issue may also serve as a place to suggest ideas to make it easier to go through activation process.

**Comment by GabLeRoux** [comment]
Another suggestion:

Show where to download the generated artifact with a screenshot
Here's a screenshot we could use:
![image](https://user-images.githubusercontent.com/1264761/95375947-5a76d100-08ae-11eb-9e02-d965893eb555.png)

**Comment by GabLeRoux** [comment]
Also, I feel like title size is not enough to differentiate the `Personal license` and `Professional license`. Only size may not be enough:
* There could be a link in the first paragraph to point to the right sections.
* There could also be entries in the sidebar to jump from one section or the other. (This would involve a bit more work).

Consider these as suggestions and can definitely be done in a different issue.

**Comment by GabLeRoux** [comment]
Another suggestion:  
I think the request activation steps could even benefit from a manual trigger so the code could be always kept in the repository, but only executed manually. More details here:  
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

**Comment by GabLeRoux** [comment]
Concerning above comment with manual trigger, here's an improved `activation.yml` which implements the above and can be used to activate any unity version (based on user input). It can be manually triggered via github actions interface:

```yaml
name: Acquire activation file
on:
  workflow_dispatch:
    inputs:
      unityVerson:
        description: 'Unity version to use during activation request'
        required: true
        default: 2020.1.7f1
jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    steps:
      # Request manual activation file
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: webbertakken/unity-request-manual-activation-file@v1.1
        with:
          unityVersion: ${{ github.event.inputs.unityVerson }}
      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
```

![image](https://user-images.githubusercontent.com/1264761/95379096-e559ca80-08b2-11eb-96d7-accd8523bd74.png)

**Comment by GabLeRoux** [comment]
I've played with github-actions again and instead of `workflow_dispatch`, I came up with a solution where we check if `UNITY_LICENSE` secret is set. If it's not set, we run the activation job, if it's set, we run the tests and the builds.

```yaml
name: Unity Actions

on:
  pull_request: {}
  push: {}

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_VERSION: 2018.3.9f1
  PROJECT_PATH: .

jobs:
  checklicense:
    name: check if UNITY_LICENSE is set in github secrets
    runs-on: ubuntu-latest
    outputs:
      is_unity_license_set: ${{ steps.checklicense_job.outputs.is_unity_license_set }}
    steps:
      - name: Check whether unity activation requests should be done
        id: checklicense_job
        run: |
            echo "Skip activation job: ${{ env.UNITY_LICENSE != '' }}"
            echo "::set-output name=is_unity_license_set::${{ env.UNITY_LICENSE != '' }}"

  activation:
    needs: [checklicense]
    if: needs.checklicense.outputs.is_unity_license_set == 'false'
    name: Request activation file 🔑
    runs-on: ubuntu-latest
    steps:
      # Request manual activation file
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: webbertakken/unity-request-manual-activation-file@master
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}

  test:
    needs: [checklicense]
    if: needs.checklicense.outputs.is_unity_license_set == 'true'
    name: Test all modes ✨
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library-test-project-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-test-project-
            Library-
      - uses: webbertakken/unity-test-runner@v1.7
        id: testRunner
        with:
          projectPath: ${{ env.UNITY_VERSION }}
          testMode: all
      - uses: actions/upload-artifact@v1
        with:
          name: Test results (all modes)
          path: ${{ steps.testRunner.outputs.artifactsPath }}

  build:
    needs: [checklicense]
    if: needs.checklicense.outputs.is_unity_license_set == 'true'
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
          - StandaloneLinux64
          - WebGL
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: webbertakken/unity-builder@v1.4
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: ${{ matrix.targetPlatform }}
          # customParameters: "-nographics"
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
```

Also note some refactors where we don't need to repeat unity versions, workflow paths, etc. I think this is the kind of workflow that can easily be sent as a PR directly to any unity github project. I'm not sure the build and test parts are working fine in here tho. [I tried on a random project on github](https://github.com/GabLeRoux/ShowMeTDD/runs/1268623016?check_suite_focus=true) and it failed, but the problem could also be the project itself ;). The conditions part did work as expected.

Here's [a more concise example of running jobs based on conditions (github-actions specific)](https://github.com/GabLeRoux/github-actions-examples/blob/main/.github/workflows/secret_based_conditions.yml)
